# Generated by Django 5.2 on 2025-04-21 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(max_length=1000, verbose_name='Video URL')),
                ('lecture_title', models.CharField(max_length=50, verbose_name='Lecture title')),
                ('lecturer', models.CharField(max_length=30, verbose_name='Lecturer')),
                ('lecture_date', models.DateField(verbose_name='Lecture date')),
                ('location', models.CharField(max_length=100, verbose_name='Lecture location')),
                ('lecture_summary', models.CharField(max_length=200, verbose_name='Summary')),
                ('lecture_length', models.DurationField(verbose_name='Video duration')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField(verbose_name='Timestamp')),
                ('label', models.CharField(max_length=100, verbose_name='Section label')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timestamps', to='vidios.lecture')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecture_topics',
            field=models.ManyToManyField(related_name='lectures', to='vidios.topic'),
        ),
    ]
