# Generated by Django 5.2 on 2025-04-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_length',
            field=models.DurationField(blank=True, null=True, verbose_name='Video duration'),
        ),
    ]
