# Generated by Django 5.2 on 2025-04-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidios', '0002_alter_lecture_lecture_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_summary',
            field=models.CharField(max_length=500, verbose_name='Summary'),
        ),
    ]
