# Generated by Django 5.2 on 2025-04-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidios', '0003_alter_lecture_lecture_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Lecturer Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='lecturer',
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecturers',
            field=models.ManyToManyField(related_name='lectures', to='vidios.lecturer', verbose_name='Lecturers'),
        ),
    ]
